### ISSUE TITLE
My Profile Does Not Show

### ISSUE THREAD

**Issue by npease18** [Legend-of-iPhoenix/UniChatDemo#11]
### Brief description of bug:
When i click on my profile link, it does not show my profile
### Expected Behavior:
It should show my profile
### Actual Behavior:
It displays:
"That user does not appear in our database, or the request was badly formatted.
Sorry!"
### How to replicate this bug:
Go to [https://legend-of-iphoenix.github.io/UniChatDemo/profile/index.html?u=LAX18](url)

**Comment by Legend-of-iPhoenix** [comment]
Ahh yes. This is an old bug, due to '0' being falsey.

Fixed: https://github.com/Legend-of-iPhoenix/UniChatDemo/commit/6b3afe6d7a4419bae4aaec1a894aadda1467ea37
