### ISSUE TITLE
Option to disable welcoming.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Legend-of-iPhoenix/UniChatDemo#27]
### Description:
You should be able to disable the "Welcome back to UniChat, user." message that is sent every time you open the page, because it becomes annoying after like the third time. We don't want to force our users to disable alerts to our webpage because that is a hassle for them.

**Comment by npease18** [comment]
Maybe We Should Get Rid of this altogether

**Comment by Legend-of-iPhoenix** [comment]
Some people enjoy it for some reason. I changed it though.

**Comment by josheewa** [comment]
There should be a settings thing to change my name, and whether or not the welcome is used.
