### ISSUE TITLE
Not really an issue, but it's look nicer if it was a bit brighter, and the title was centered

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#30]
Not really an issue, but it's look nicer if it was a bit brighter, and the title was centered

 If you are requesting a title change: (yes?)

Title Requested: A stupid guy making dumb suggestions

UniChat Username: jcgter777

Why you deserve this title: Because I did do that :P

**Comment by Legend-of-iPhoenix** [comment]
Added bug label, because the title *should* be centered.

**Comment by Legend-of-iPhoenix** [comment]
Partially fixed in https://github.com/Legend-of-iPhoenix/UniChatDemo/commit/b59c05bc7e74085ef17b44f4f22364c0f8bb34a6

**Comment by Legend-of-iPhoenix** [comment]
Accidentally closed issue :/

**Comment by Legend-of-iPhoenix** [comment]
ARGG I DID IT AGAIN

**Comment by josheewa** [comment]
hehe

**Comment by josheewa** [comment]
@Legend-of-iPhoenix now, the buttons need to be centered :P

**Comment by npease18** [comment]
The nav bar is completely replaced so this issue is obsolete.
