### ISSUE TITLE
Bots are disabled

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#32]
Why is it that the bots are sometimes off and sometimes on? 

EDIT: could there possibly be an online database to store the bots?

**Comment by Legend-of-iPhoenix** [comment]
1) They are running on my laptop, which ran out of "juice" last night. :(
2) No, unfortunately, for security reasons.

**Comment by josheewa** [comment]
Awww. Juice it up!
