### ISSUE TITLE
Extension being stupid. (sorry, just upset that I'm being duplicated :P))

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#41]
I found a bug. 

When I send messages through the extension, it duplicates my username, and in the chat room uses [null] to substitute jcgter777, and in the active user list, there are two jcgter777's. Is this just the extension? Or is it the whole thing?

**Comment by Legend-of-iPhoenix** [comment]
It's broken due to the changes submitted yesterday. I hope to fix it today.
