### ISSUE TITLE
Color of title image doesn't match

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#45]
The image made by LAX 18 has a different background color than the website. It used to look mended together, but not now.

**Comment by Legend-of-iPhoenix** [comment]
Yeah, that's because of changes I made to you other issue. I'll give it a border and it'll look awesome even with the changed color!

**Comment by josheewa** [comment]
Can I make another picture? :P

**Comment by npease18** [comment]
Go for it! That was a very basic image

**Comment by josheewa** [comment]
YAY!! Thanks, @LAX18!

**Comment by npease18** [comment]
Yeah Im not too attached to it

**Comment by npease18** [comment]
BUT LEAVE THE FAVICON ALONE!!!

**Comment by josheewa** [comment]
@Legend-of-iPhoenix and @LAX18 What font should I use for "UniChat"? (I like syncopate)

**Comment by npease18** [comment]
Its not bad... i used this for the title:
[https://cooltext.com/Logo-Design-Chrome-One](url)

**Comment by josheewa** [comment]
@LAX18 broken link. Also, what's da favicon?

**Comment by npease18** [comment]
the favicon is the image that is in the tab of the browser

**Comment by josheewa** [comment]
I just found out :P (Google)

**Comment by npease18** [comment]
The font is from cooltext.com and is called "Chrome One"

**Comment by josheewa** [comment]
ok: I made it:
![screen shot 2018-01-21 at 5 44 34 pm](https://user-images.githubusercontent.com/34496783/35199888-d32e014c-fed2-11e7-8b20-74fc37090223.png)

**Comment by npease18** [comment]
Its not bad...

**Comment by josheewa** [comment]
I screenshotted off of google slides, so you can tell me what needs to be done :P

**Comment by npease18** [comment]
so make it a image

**Comment by josheewa** [comment]
It is an image

**Comment by npease18** [comment]
download the google slides as a image

**Comment by josheewa** [comment]
![screen shot 2018-01-21 at 5 47 26 pm](https://user-images.githubusercontent.com/34496783/35199911-2d82e9aa-fed3-11e7-818c-9ec794acd184.png)

**Comment by npease18** [comment]
then post it on imgur
copy the image url
paste it in the index.html file

**Comment by josheewa** [comment]
I know that. Is that better? @Legend-of-iPhoenix and @LAX18

**Comment by josheewa** [comment]
whoops. Ok. I think I need to crop it, tho. @LAX18 I might just go with the screen

**Comment by npease18** [comment]
I think it is great!

**Comment by josheewa** [comment]
@Legend-of-iPhoenix and @LAX18 : https://i.imgur.com/XWYqGtZ.png

**Comment by npease18** [comment]
sure

**Comment by josheewa** [comment]
@LAX18 I made a PR

**Comment by npease18** [comment]
Accepted!

**Comment by josheewa** [comment]
YAY!

**Comment by josheewa** [comment]
Getting rejected makes me smad

**Comment by josheewa** [comment]
@LAX18 Do you know why?

**Comment by npease18** [comment]
do i know what?

**Comment by josheewa** [comment]
nvm iPhoenix told me

**Comment by Legend-of-iPhoenix** [comment]
<3
