### ISSUE TITLE
What's wrong with not being able to send messages? 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#63]
Will the update tonight fix this issue?

**Comment by josheewa** [comment]
@Legend-of-iPhoenix

**Comment by npease18** [comment]
I hope so....

**Comment by Legend-of-iPhoenix** [comment]
Yes, it should. I know exactly what is wrong.  Additionally, please refrain from double "posting" 👍 

The edit button exists for a reason <3
