### ISSUE TITLE
The navigation bar is transparent

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#66]
It looks weird when scrolling. It's not that bad, but... it could be fixed.

**Comment by Legend-of-iPhoenix** [comment]
Please elaborate on this. Screenshots would be really nice.

**Comment by josheewa** [comment]
When i scroll, I can see the text behind the nav bar. @Legend-of-iPhoenix

**Comment by josheewa** [comment]
![screen shot 2018-01-23 at 4 05 13 pm](https://user-images.githubusercontent.com/34496783/35300687-40228b12-0057-11e8-87e0-42cdb424e49c.png)
@Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
This was a simple z-index issue. Fixed!
