### ISSUE TITLE
The extension automatically exits, even though I already set a username. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#69]
I think (more like know) that this is caused by the new pointers for userIDs, but can you make usernames not be able to be duplicated anywhere?

Even though the extension glitches, my duplicated username still appears in the box. 

I know that this is probably already known, but, make it an issue so it'll be remembered. 

![screen shot 2018-01-22 at 9 32 17 pm](https://user-images.githubusercontent.com/34496783/35255181-ceaa8ea8-ffbb-11e7-89fd-9956aa2c0f1e.png)
^^Example^^

**Comment by Legend-of-iPhoenix** [comment]
This is caused by the UIDS, but there is some unexpected JS weirdness happening.
