### ISSUE TITLE
Changing PMs and actions in notifications. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#74]
When I get notified of a highlight from an action or PM, it shows "/pm" instead of maybe "[PM][iPhoenix->You] Hello there"
Same thing with actions. (/me)

**Comment by Legend-of-iPhoenix** [comment]
Fixed in https://github.com/Legend-of-iPhoenix/UniChatDemo/commit/df23d3201b8d14dde86a3c26ac957b09e4eacbc8
