### ISSUE TITLE
Delete Stats Page

### ISSUE THREAD

**Issue by npease18** [Legend-of-iPhoenix/UniChatDemo#76]
The stats page is outdated, not linked to anywhere, and has been replaced by /about/index.html. I believe the next step to be deleting the stats folder and content. The message totals are available on the about page. Would this interfere with the operation of the about page? @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
Well, if you move the js from the stats page to the about page, and we update the stats page to work, then yeah! I'll get started rn.

**Comment by Legend-of-iPhoenix** [comment]
Done!
