### ISSUE TITLE
With the new Markdown things, URLs become broken. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#78]
https://github.com/lax18/markup-language became  https:github.com/lax18markup-language

**Comment by npease18** [comment]
Expected Result: [https://github.com/LAX18/Markup-Language](url)

**Comment by josheewa** [comment]
Even more. all the /'s make text italic :/

**Comment by Legend-of-iPhoenix** [comment]
Thanks for the report!

**Comment by Legend-of-iPhoenix** [comment]
lol

**Comment by npease18** [comment]
Sorry just tried to add it as you did

**Comment by npease18** [comment]
lol

**Comment by josheewa** [comment]
omfg, stahp spamming
