### ISSUE TITLE
Add a Cemetech thread link somewhere

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#83]
nothing to add

**Comment by Legend-of-iPhoenix** [comment]
There *is*

Scroll down (all the way), and click on the word "UniChat"

**Comment by Legend-of-iPhoenix** [comment]
There *is*

Scroll down (all the way), and click on the word "UniChat"

**Comment by josheewa** [comment]
it should be clearer
