### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#92]
@Legend-of-iPhoenix 

Can i include a fire emoji in ~kiwf for jcgterBOT and DoorsCE? If you don't want it, just delete it. In the API, it makes the emoji into weird chars. If that will happen to the emoji in the actual chat, the delete it as well. (Please include the reason)

**Comment by Legend-of-iPhoenix** [comment]
I'll create a UniChat fire emote, because that's one of about 3 things I'm good at drawing.

**Comment by josheewa** [comment]
I meant that I already included a copy and paste emoji in my code. Will that show up on UniChat? I've done it directly before, but I don't know about now, and through bots. @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
I will, but I'd rather use our custom emotes.

**Comment by josheewa** [comment]
kk
