### ISSUE TITLE
Different tabs have different online statuses

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#95]
I opened 2 tabs of UniChat, and I was only listed once. I opened one 30 mins later than the other. I found out that I had two, and when I closed the new one, it said I was offline.

**Comment by Legend-of-iPhoenix** [comment]
You are marked as inactive whenever you close a tab or haven't posted a message in ~15 minutes (IIRC)

It doesn't know whether you still have a tab open or not.

**Comment by josheewa** [comment]
makes sense
