### ISSUE TITLE
Typing messages while offline isn't secret. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#96]
I was testing what would happen while typing offline, and what happened was that the text disappeared after I pressed enter, but nothing came up. When I connected back to wifi, the messages I typed were suddenly on there, and at the right times. HOW?!?!

**Comment by Legend-of-iPhoenix** [comment]
1) The data is sent right as you reconnect
2) The timestamp is not when the message gets to the server, rather, it is recorded and stored when you send it.
3) The messages reorder themselves based on timestamp when you reload or every 15 seconds.

**Comment by josheewa** [comment]
cool
