### ISSUE TITLE
Highlighting users with names under 4 characters?

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/UniChatDemo#99]
How do you highlight someone when their username is less than 4 chars? You have to type everything, right? Or is there a shorter way? @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
Yes, you have to type everything.

**Comment by josheewa** [comment]
That makes sense. It was user ab that made me think of this. Also like PT_ :P
